site_name: nrkdownload
site_url: !ENV READTHEDOCS_CANONICAL_URL
repo_url: https://github.com/marhoy/nrk-download
repo_name: marhoy/nrk-download

nav:
  - Home: index.md
  - Features: features.md
  - Installation:
      - nrkdownload: installing-nrkdownload.md
      - FFmpeg: installing-ffmpeg.md
  - Usage:
      - Usage: usage.md
      - Examples: examples.md
  - Contributing: contributing.md

theme:
  name: material
  palette:
    primary: light blue
  favicon: images/favicon.ico
  icon:
    logo: material/monitor-arrow-down
    repo: fontawesome/brands/github
  custom_dir: docs/overrides
  features:
    - navigation.expand
    - navigation.footer
    - content.code.copy
    - search.highlight
    - search.share

extra:
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

extra_javascript:
  #  - javascript/readthedocs-search.js
  - javascript/readthedocs-menu.js
