name: Test coverage
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-22.04 # FFmpeg core-dumps on 22.04/24.04
    steps:
      - name: Install FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        id: setup-ffmpeg
        with:
          ffmpeg-version: git

      - name: Test FFmpeg
        run: ffmpeg -version

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ vars.UV_VERSION }}

      - name: Install the project with dependencies
        run: uv sync

      - name: Run tests
        run: uv run pytest --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          slug: marhoy/nrk-download
          token: ${{ secrets.CODECOV_TOKEN }}
